### ISSUE TITLE
suggest nested-diff ignore_nan feature.

### ISSUE THREAD

**Issue by qihangy** [mr-mixas/Nested-Diff.py#5]
Hello Michael, 

I really like your nested-diff here and it is nice and clean, specially the text formatter feature.

However, I found the diff function currently does not support ignoring the nan’s while comparing items. Is it possible that this feature can be added to the next release? 

Here is my pesudo suggestions: 
if ignore_nan and isinstance(x, float) and str(x) == str(y) == 'nan':
     then not store in "D"
     
Thank you.

**Comment by mr-mixas** [comment]
Hi, 

I thought again, and again, and... you are right :)
There should be builtin opt for ignoring difference between NaN instances.

I added `nans_equal` opt to float handler and `extra_handlers` opt to `diff`.
Since v1.2 NaNs difference ignoring using `diff` function is just

```
>>> from nested_diff import diff, handlers
>>> 
>>> diff(float('nan'), float('nan'), extra_handlers=[handlers.FloatHandler(nans_equal=True)])
{'U': nan}
>>> 
```

Hope it helps =)

**Comment by qihangy** [comment]
Oh, thanks man! That’s very helpful :)
